/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Query type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Query{}

// Query Description of a query in the system
type Query struct {
	// ID of selected Query (I propose UUID, but it is under your own discretion)
	QueryId string `json:"queryId"`
	Status QueryStatus `json:"status"`
	// Whether result of this query is already available
	IsResultAvailable *bool `json:"isResultAvailable,omitempty"`
	QueryDefinition QueryQueryDefinition `json:"queryDefinition"`
}

type _Query Query

// NewQuery instantiates a new Query object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuery(queryId string, status QueryStatus, queryDefinition QueryQueryDefinition) *Query {
	this := Query{}
	this.QueryId = queryId
	this.Status = status
	this.QueryDefinition = queryDefinition
	return &this
}

// NewQueryWithDefaults instantiates a new Query object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryWithDefaults() *Query {
	this := Query{}
	return &this
}

// GetQueryId returns the QueryId field value
func (o *Query) GetQueryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QueryId
}

// GetQueryIdOk returns a tuple with the QueryId field value
// and a boolean to check if the value has been set.
func (o *Query) GetQueryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QueryId, true
}

// SetQueryId sets field value
func (o *Query) SetQueryId(v string) {
	o.QueryId = v
}

// GetStatus returns the Status field value
func (o *Query) GetStatus() QueryStatus {
	if o == nil {
		var ret QueryStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Query) GetStatusOk() (*QueryStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Query) SetStatus(v QueryStatus) {
	o.Status = v
}

// GetIsResultAvailable returns the IsResultAvailable field value if set, zero value otherwise.
func (o *Query) GetIsResultAvailable() bool {
	if o == nil || IsNil(o.IsResultAvailable) {
		var ret bool
		return ret
	}
	return *o.IsResultAvailable
}

// GetIsResultAvailableOk returns a tuple with the IsResultAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Query) GetIsResultAvailableOk() (*bool, bool) {
	if o == nil || IsNil(o.IsResultAvailable) {
		return nil, false
	}
	return o.IsResultAvailable, true
}

// HasIsResultAvailable returns a boolean if a field has been set.
func (o *Query) HasIsResultAvailable() bool {
	if o != nil && !IsNil(o.IsResultAvailable) {
		return true
	}

	return false
}

// SetIsResultAvailable gets a reference to the given bool and assigns it to the IsResultAvailable field.
func (o *Query) SetIsResultAvailable(v bool) {
	o.IsResultAvailable = &v
}

// GetQueryDefinition returns the QueryDefinition field value
func (o *Query) GetQueryDefinition() QueryQueryDefinition {
	if o == nil {
		var ret QueryQueryDefinition
		return ret
	}

	return o.QueryDefinition
}

// GetQueryDefinitionOk returns a tuple with the QueryDefinition field value
// and a boolean to check if the value has been set.
func (o *Query) GetQueryDefinitionOk() (*QueryQueryDefinition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QueryDefinition, true
}

// SetQueryDefinition sets field value
func (o *Query) SetQueryDefinition(v QueryQueryDefinition) {
	o.QueryDefinition = v
}

func (o Query) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Query) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["queryId"] = o.QueryId
	toSerialize["status"] = o.Status
	if !IsNil(o.IsResultAvailable) {
		toSerialize["isResultAvailable"] = o.IsResultAvailable
	}
	toSerialize["queryDefinition"] = o.QueryDefinition
	return toSerialize, nil
}

func (o *Query) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"queryId",
		"status",
		"queryDefinition",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuery := _Query{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuery)

	if err != nil {
		return err
	}

	*o = Query(varQuery)

	return err
}

type NullableQuery struct {
	value *Query
	isSet bool
}

func (v NullableQuery) Get() *Query {
	return v.value
}

func (v *NullableQuery) Set(val *Query) {
	v.value = val
	v.isSet = true
}

func (v NullableQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuery(val *Query) *NullableQuery {
	return &NullableQuery{value: val, isSet: true}
}

func (v NullableQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


