/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Literal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Literal{}

// Literal Description of a literal value used in column expression
type Literal struct {
	Value *LiteralValue `json:"value,omitempty"`
}

// NewLiteral instantiates a new Literal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLiteral() *Literal {
	this := Literal{}
	return &this
}

// NewLiteralWithDefaults instantiates a new Literal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLiteralWithDefaults() *Literal {
	this := Literal{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *Literal) GetValue() LiteralValue {
	if o == nil || IsNil(o.Value) {
		var ret LiteralValue
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Literal) GetValueOk() (*LiteralValue, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *Literal) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given LiteralValue and assigns it to the Value field.
func (o *Literal) SetValue(v LiteralValue) {
	o.Value = &v
}

func (o Literal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Literal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableLiteral struct {
	value *Literal
	isSet bool
}

func (v NullableLiteral) Get() *Literal {
	return v.value
}

func (v *NullableLiteral) Set(val *Literal) {
	v.value = val
	v.isSet = true
}

func (v NullableLiteral) IsSet() bool {
	return v.isSet
}

func (v *NullableLiteral) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiteral(val *Literal) *NullableLiteral {
	return &NullableLiteral{value: val, isSet: true}
}

func (v NullableLiteral) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLiteral) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


