/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ShallowQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShallowQuery{}

// ShallowQuery Description of a shallow representation of a query
type ShallowQuery struct {
	// ID of selected Query (I propose UUID, but it is under your own discretion)
	QueryId string `json:"queryId"`
	Status QueryStatus `json:"status"`
}

type _ShallowQuery ShallowQuery

// NewShallowQuery instantiates a new ShallowQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShallowQuery(queryId string, status QueryStatus) *ShallowQuery {
	this := ShallowQuery{}
	this.QueryId = queryId
	this.Status = status
	return &this
}

// NewShallowQueryWithDefaults instantiates a new ShallowQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShallowQueryWithDefaults() *ShallowQuery {
	this := ShallowQuery{}
	return &this
}

// GetQueryId returns the QueryId field value
func (o *ShallowQuery) GetQueryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QueryId
}

// GetQueryIdOk returns a tuple with the QueryId field value
// and a boolean to check if the value has been set.
func (o *ShallowQuery) GetQueryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QueryId, true
}

// SetQueryId sets field value
func (o *ShallowQuery) SetQueryId(v string) {
	o.QueryId = v
}

// GetStatus returns the Status field value
func (o *ShallowQuery) GetStatus() QueryStatus {
	if o == nil {
		var ret QueryStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ShallowQuery) GetStatusOk() (*QueryStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ShallowQuery) SetStatus(v QueryStatus) {
	o.Status = v
}

func (o ShallowQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShallowQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["queryId"] = o.QueryId
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *ShallowQuery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"queryId",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShallowQuery := _ShallowQuery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShallowQuery)

	if err != nil {
		return err
	}

	*o = ShallowQuery(varShallowQuery)

	return err
}

type NullableShallowQuery struct {
	value *ShallowQuery
	isSet bool
}

func (v NullableShallowQuery) Get() *ShallowQuery {
	return v.value
}

func (v *NullableShallowQuery) Set(val *ShallowQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableShallowQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableShallowQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShallowQuery(val *ShallowQuery) *NullableShallowQuery {
	return &NullableShallowQuery{value: val, isSet: true}
}

func (v NullableShallowQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShallowQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


