/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TableSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableSchema{}

// TableSchema Description of the table in the database
type TableSchema struct {
	Name string `json:"name"`
	Columns []Column `json:"columns"`
}

type _TableSchema TableSchema

// NewTableSchema instantiates a new TableSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableSchema(name string, columns []Column) *TableSchema {
	this := TableSchema{}
	this.Name = name
	this.Columns = columns
	return &this
}

// NewTableSchemaWithDefaults instantiates a new TableSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableSchemaWithDefaults() *TableSchema {
	this := TableSchema{}
	return &this
}

// GetName returns the Name field value
func (o *TableSchema) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TableSchema) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TableSchema) SetName(v string) {
	o.Name = v
}

// GetColumns returns the Columns field value
func (o *TableSchema) GetColumns() []Column {
	if o == nil {
		var ret []Column
		return ret
	}

	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value
// and a boolean to check if the value has been set.
func (o *TableSchema) GetColumnsOk() ([]Column, bool) {
	if o == nil {
		return nil, false
	}
	return o.Columns, true
}

// SetColumns sets field value
func (o *TableSchema) SetColumns(v []Column) {
	o.Columns = v
}

func (o TableSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["columns"] = o.Columns
	return toSerialize, nil
}

func (o *TableSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"columns",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTableSchema := _TableSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTableSchema)

	if err != nil {
		return err
	}

	*o = TableSchema(varTableSchema)

	return err
}

type NullableTableSchema struct {
	value *TableSchema
	isSet bool
}

func (v NullableTableSchema) Get() *TableSchema {
	return v.value
}

func (v *NullableTableSchema) Set(val *TableSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableTableSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableTableSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableSchema(val *TableSchema) *NullableTableSchema {
	return &NullableTableSchema{value: val, isSet: true}
}

func (v NullableTableSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


