/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ColumnarUnaryOperation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ColumnarUnaryOperation{}

// ColumnarUnaryOperation Description of unary Operation
type ColumnarUnaryOperation struct {
	Operand *ColumnExpression `json:"operand,omitempty"`
	Operator *string `json:"operator,omitempty"`
}

// NewColumnarUnaryOperation instantiates a new ColumnarUnaryOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewColumnarUnaryOperation() *ColumnarUnaryOperation {
	this := ColumnarUnaryOperation{}
	return &this
}

// NewColumnarUnaryOperationWithDefaults instantiates a new ColumnarUnaryOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewColumnarUnaryOperationWithDefaults() *ColumnarUnaryOperation {
	this := ColumnarUnaryOperation{}
	return &this
}

// GetOperand returns the Operand field value if set, zero value otherwise.
func (o *ColumnarUnaryOperation) GetOperand() ColumnExpression {
	if o == nil || IsNil(o.Operand) {
		var ret ColumnExpression
		return ret
	}
	return *o.Operand
}

// GetOperandOk returns a tuple with the Operand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColumnarUnaryOperation) GetOperandOk() (*ColumnExpression, bool) {
	if o == nil || IsNil(o.Operand) {
		return nil, false
	}
	return o.Operand, true
}

// HasOperand returns a boolean if a field has been set.
func (o *ColumnarUnaryOperation) HasOperand() bool {
	if o != nil && !IsNil(o.Operand) {
		return true
	}

	return false
}

// SetOperand gets a reference to the given ColumnExpression and assigns it to the Operand field.
func (o *ColumnarUnaryOperation) SetOperand(v ColumnExpression) {
	o.Operand = &v
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *ColumnarUnaryOperation) GetOperator() string {
	if o == nil || IsNil(o.Operator) {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColumnarUnaryOperation) GetOperatorOk() (*string, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *ColumnarUnaryOperation) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *ColumnarUnaryOperation) SetOperator(v string) {
	o.Operator = &v
}

func (o ColumnarUnaryOperation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ColumnarUnaryOperation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Operand) {
		toSerialize["operand"] = o.Operand
	}
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	return toSerialize, nil
}

type NullableColumnarUnaryOperation struct {
	value *ColumnarUnaryOperation
	isSet bool
}

func (v NullableColumnarUnaryOperation) Get() *ColumnarUnaryOperation {
	return v.value
}

func (v *NullableColumnarUnaryOperation) Set(val *ColumnarUnaryOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableColumnarUnaryOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableColumnarUnaryOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableColumnarUnaryOperation(val *ColumnarUnaryOperation) *NullableColumnarUnaryOperation {
	return &NullableColumnarUnaryOperation{value: val, isSet: true}
}

func (v NullableColumnarUnaryOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableColumnarUnaryOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


