/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// LogicalColumnType Enum describing logical column types
type LogicalColumnType string

// List of LogicalColumnType
const (
	INT64 LogicalColumnType = "INT64"
	VARCHAR LogicalColumnType = "VARCHAR"
)

// All allowed values of LogicalColumnType enum
var AllowedLogicalColumnTypeEnumValues = []LogicalColumnType{
	"INT64",
	"VARCHAR",
}

func (v *LogicalColumnType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LogicalColumnType(value)
	for _, existing := range AllowedLogicalColumnTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LogicalColumnType", value)
}

// NewLogicalColumnTypeFromValue returns a pointer to a valid LogicalColumnType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLogicalColumnTypeFromValue(v string) (*LogicalColumnType, error) {
	ev := LogicalColumnType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LogicalColumnType: valid values are %v", v, AllowedLogicalColumnTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LogicalColumnType) IsValid() bool {
	for _, existing := range AllowedLogicalColumnTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to LogicalColumnType value
func (v LogicalColumnType) Ptr() *LogicalColumnType {
	return &v
}

type NullableLogicalColumnType struct {
	value *LogicalColumnType
	isSet bool
}

func (v NullableLogicalColumnType) Get() *LogicalColumnType {
	return v.value
}

func (v *NullableLogicalColumnType) Set(val *LogicalColumnType) {
	v.value = val
	v.isSet = true
}

func (v NullableLogicalColumnType) IsSet() bool {
	return v.isSet
}

func (v *NullableLogicalColumnType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogicalColumnType(val *LogicalColumnType) *NullableLogicalColumnType {
	return &NullableLogicalColumnType{value: val, isSet: true}
}

func (v NullableLogicalColumnType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogicalColumnType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

