/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ColumnarBinaryOperation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ColumnarBinaryOperation{}

// ColumnarBinaryOperation Description of columnar operator used in column expression
type ColumnarBinaryOperation struct {
	Operator *string `json:"operator,omitempty"`
	LeftOperand *ColumnExpression `json:"leftOperand,omitempty"`
	RightOperand *ColumnExpression `json:"rightOperand,omitempty"`
}

// NewColumnarBinaryOperation instantiates a new ColumnarBinaryOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewColumnarBinaryOperation() *ColumnarBinaryOperation {
	this := ColumnarBinaryOperation{}
	return &this
}

// NewColumnarBinaryOperationWithDefaults instantiates a new ColumnarBinaryOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewColumnarBinaryOperationWithDefaults() *ColumnarBinaryOperation {
	this := ColumnarBinaryOperation{}
	return &this
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *ColumnarBinaryOperation) GetOperator() string {
	if o == nil || IsNil(o.Operator) {
		var ret string
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColumnarBinaryOperation) GetOperatorOk() (*string, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *ColumnarBinaryOperation) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given string and assigns it to the Operator field.
func (o *ColumnarBinaryOperation) SetOperator(v string) {
	o.Operator = &v
}

// GetLeftOperand returns the LeftOperand field value if set, zero value otherwise.
func (o *ColumnarBinaryOperation) GetLeftOperand() ColumnExpression {
	if o == nil || IsNil(o.LeftOperand) {
		var ret ColumnExpression
		return ret
	}
	return *o.LeftOperand
}

// GetLeftOperandOk returns a tuple with the LeftOperand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColumnarBinaryOperation) GetLeftOperandOk() (*ColumnExpression, bool) {
	if o == nil || IsNil(o.LeftOperand) {
		return nil, false
	}
	return o.LeftOperand, true
}

// HasLeftOperand returns a boolean if a field has been set.
func (o *ColumnarBinaryOperation) HasLeftOperand() bool {
	if o != nil && !IsNil(o.LeftOperand) {
		return true
	}

	return false
}

// SetLeftOperand gets a reference to the given ColumnExpression and assigns it to the LeftOperand field.
func (o *ColumnarBinaryOperation) SetLeftOperand(v ColumnExpression) {
	o.LeftOperand = &v
}

// GetRightOperand returns the RightOperand field value if set, zero value otherwise.
func (o *ColumnarBinaryOperation) GetRightOperand() ColumnExpression {
	if o == nil || IsNil(o.RightOperand) {
		var ret ColumnExpression
		return ret
	}
	return *o.RightOperand
}

// GetRightOperandOk returns a tuple with the RightOperand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColumnarBinaryOperation) GetRightOperandOk() (*ColumnExpression, bool) {
	if o == nil || IsNil(o.RightOperand) {
		return nil, false
	}
	return o.RightOperand, true
}

// HasRightOperand returns a boolean if a field has been set.
func (o *ColumnarBinaryOperation) HasRightOperand() bool {
	if o != nil && !IsNil(o.RightOperand) {
		return true
	}

	return false
}

// SetRightOperand gets a reference to the given ColumnExpression and assigns it to the RightOperand field.
func (o *ColumnarBinaryOperation) SetRightOperand(v ColumnExpression) {
	o.RightOperand = &v
}

func (o ColumnarBinaryOperation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ColumnarBinaryOperation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	if !IsNil(o.LeftOperand) {
		toSerialize["leftOperand"] = o.LeftOperand
	}
	if !IsNil(o.RightOperand) {
		toSerialize["rightOperand"] = o.RightOperand
	}
	return toSerialize, nil
}

type NullableColumnarBinaryOperation struct {
	value *ColumnarBinaryOperation
	isSet bool
}

func (v NullableColumnarBinaryOperation) Get() *ColumnarBinaryOperation {
	return v.value
}

func (v *NullableColumnarBinaryOperation) Set(val *ColumnarBinaryOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableColumnarBinaryOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableColumnarBinaryOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableColumnarBinaryOperation(val *ColumnarBinaryOperation) *NullableColumnarBinaryOperation {
	return &NullableColumnarBinaryOperation{value: val, isSet: true}
}

func (v NullableColumnarBinaryOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableColumnarBinaryOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


