/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LimitExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LimitExpression{}

// LimitExpression Description of LIMIT clause in SELECT query
type LimitExpression struct {
	Limit *int32 `json:"limit,omitempty"`
}

// NewLimitExpression instantiates a new LimitExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLimitExpression() *LimitExpression {
	this := LimitExpression{}
	return &this
}

// NewLimitExpressionWithDefaults instantiates a new LimitExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLimitExpressionWithDefaults() *LimitExpression {
	this := LimitExpression{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *LimitExpression) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LimitExpression) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *LimitExpression) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *LimitExpression) SetLimit(v int32) {
	o.Limit = &v
}

func (o LimitExpression) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LimitExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	return toSerialize, nil
}

type NullableLimitExpression struct {
	value *LimitExpression
	isSet bool
}

func (v NullableLimitExpression) Get() *LimitExpression {
	return v.value
}

func (v *NullableLimitExpression) Set(val *LimitExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableLimitExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableLimitExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLimitExpression(val *LimitExpression) *NullableLimitExpression {
	return &NullableLimitExpression{value: val, isSet: true}
}

func (v NullableLimitExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLimitExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


