// Code generated by pigeon; DO NOT EDIT.

// Package parser provides SQL parsing for a subset of SQL
// that maps to the ISBD DBMS OpenAPI interface.
//
// This file is the source of truth for the SQL grammar.
// To regenerate the parser, run:
//   go generate ./...
//
// Grammar supports:
//   - SELECT with column expressions
//   - FROM clause (optional, table name is parsed but not stored)
//   - WHERE clause with boolean expressions
//   - ORDER BY clause (by column index, ASC/DESC)
//   - LIMIT clause
//   - Arithmetic operators: +, -, *, /
//   - Comparison operators: =, <>, !=, <, <=, >, >=
//   - Logical operators: AND, OR, NOT
//   - Functions: STRLEN, CONCAT, UPPER, LOWER
//   - Literals: integers, strings, TRUE, FALSE
//   - Column references: column or table.column

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Query",
			pos:  position{line: 33, col: 1, offset: 1010},
			expr: &actionExpr{
				pos: position{line: 33, col: 10, offset: 1019},
				run: (*parser).callonQuery1,
				expr: &seqExpr{
					pos: position{line: 33, col: 10, offset: 1019},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 33, col: 10, offset: 1019},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 33, col: 12, offset: 1021},
							val:        "select",
							ignoreCase: true,
							want:       "\"SELECT\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 22, offset: 1031},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 33, col: 24, offset: 1033},
							label: "columns",
							expr: &ruleRefExpr{
								pos:  position{line: 33, col: 32, offset: 1041},
								name: "ColumnList",
							},
						},
						&labeledExpr{
							pos:   position{line: 33, col: 43, offset: 1052},
							label: "from",
							expr: &zeroOrOneExpr{
								pos: position{line: 33, col: 48, offset: 1057},
								expr: &ruleRefExpr{
									pos:  position{line: 33, col: 48, offset: 1057},
									name: "FromClause",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 33, col: 60, offset: 1069},
							label: "where",
							expr: &zeroOrOneExpr{
								pos: position{line: 33, col: 66, offset: 1075},
								expr: &ruleRefExpr{
									pos:  position{line: 33, col: 66, offset: 1075},
									name: "WhereClause",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 34, col: 10, offset: 1098},
							label: "orderBy",
							expr: &zeroOrOneExpr{
								pos: position{line: 34, col: 18, offset: 1106},
								expr: &ruleRefExpr{
									pos:  position{line: 34, col: 18, offset: 1106},
									name: "OrderByClause",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 34, col: 33, offset: 1121},
							label: "limit",
							expr: &zeroOrOneExpr{
								pos: position{line: 34, col: 39, offset: 1127},
								expr: &ruleRefExpr{
									pos:  position{line: 34, col: 39, offset: 1127},
									name: "LimitClause",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 34, col: 52, offset: 1140},
							name: "_",
						},
						&zeroOrOneExpr{
							pos: position{line: 34, col: 54, offset: 1142},
							expr: &litMatcher{
								pos:        position{line: 34, col: 54, offset: 1142},
								val:        ";",
								ignoreCase: false,
								want:       "\";\"",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 34, col: 59, offset: 1147},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 34, col: 61, offset: 1149},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "ColumnList",
			pos:  position{line: 42, col: 1, offset: 1395},
			expr: &actionExpr{
				pos: position{line: 42, col: 15, offset: 1409},
				run: (*parser).callonColumnList1,
				expr: &seqExpr{
					pos: position{line: 42, col: 15, offset: 1409},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 42, col: 15, offset: 1409},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 42, col: 21, offset: 1415},
								name: "Expr",
							},
						},
						&labeledExpr{
							pos:   position{line: 42, col: 26, offset: 1420},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 42, col: 31, offset: 1425},
								expr: &actionExpr{
									pos: position{line: 42, col: 33, offset: 1427},
									run: (*parser).callonColumnList7,
									expr: &seqExpr{
										pos: position{line: 42, col: 33, offset: 1427},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 42, col: 33, offset: 1427},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 42, col: 35, offset: 1429},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
											&ruleRefExpr{
												pos:  position{line: 42, col: 39, offset: 1433},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 42, col: 41, offset: 1435},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 42, col: 43, offset: 1437},
													name: "Expr",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "FromClause",
			pos:  position{line: 46, col: 1, offset: 1513},
			expr: &actionExpr{
				pos: position{line: 46, col: 15, offset: 1527},
				run: (*parser).callonFromClause1,
				expr: &seqExpr{
					pos: position{line: 46, col: 15, offset: 1527},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 46, col: 15, offset: 1527},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 46, col: 17, offset: 1529},
							val:        "from",
							ignoreCase: true,
							want:       "\"FROM\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 25, offset: 1537},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 27, offset: 1539},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 33, offset: 1545},
								name: "Identifier",
							},
						},
						&labeledExpr{
							pos:   position{line: 46, col: 44, offset: 1556},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 46, col: 49, offset: 1561},
								expr: &actionExpr{
									pos: position{line: 46, col: 51, offset: 1563},
									run: (*parser).callonFromClause10,
									expr: &seqExpr{
										pos: position{line: 46, col: 51, offset: 1563},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 46, col: 51, offset: 1563},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 46, col: 53, offset: 1565},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
											&ruleRefExpr{
												pos:  position{line: 46, col: 57, offset: 1569},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 46, col: 59, offset: 1571},
												label: "name",
												expr: &ruleRefExpr{
													pos:  position{line: 46, col: 64, offset: 1576},
													name: "Identifier",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "WhereClause",
			pos:  position{line: 51, col: 1, offset: 1659},
			expr: &actionExpr{
				pos: position{line: 51, col: 16, offset: 1674},
				run: (*parser).callonWhereClause1,
				expr: &seqExpr{
					pos: position{line: 51, col: 16, offset: 1674},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 51, col: 16, offset: 1674},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 51, col: 18, offset: 1676},
							val:        "where",
							ignoreCase: true,
							want:       "\"WHERE\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 51, col: 27, offset: 1685},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 51, col: 29, offset: 1687},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 51, col: 34, offset: 1692},
								name: "Expr",
							},
						},
					},
				},
			},
		},
		{
			name: "OrderByClause",
			pos:  position{line: 55, col: 1, offset: 1723},
			expr: &actionExpr{
				pos: position{line: 55, col: 18, offset: 1740},
				run: (*parser).callonOrderByClause1,
				expr: &seqExpr{
					pos: position{line: 55, col: 18, offset: 1740},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 55, col: 18, offset: 1740},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 55, col: 20, offset: 1742},
							val:        "order",
							ignoreCase: true,
							want:       "\"ORDER\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 29, offset: 1751},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 55, col: 31, offset: 1753},
							val:        "by",
							ignoreCase: true,
							want:       "\"BY\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 55, col: 37, offset: 1759},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 55, col: 39, offset: 1761},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 55, col: 45, offset: 1767},
								name: "OrderByItem",
							},
						},
						&labeledExpr{
							pos:   position{line: 55, col: 57, offset: 1779},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 55, col: 62, offset: 1784},
								expr: &actionExpr{
									pos: position{line: 55, col: 64, offset: 1786},
									run: (*parser).callonOrderByClause12,
									expr: &seqExpr{
										pos: position{line: 55, col: 64, offset: 1786},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 55, col: 64, offset: 1786},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 55, col: 66, offset: 1788},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
											&ruleRefExpr{
												pos:  position{line: 55, col: 70, offset: 1792},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 55, col: 72, offset: 1794},
												label: "o",
												expr: &ruleRefExpr{
													pos:  position{line: 55, col: 74, offset: 1796},
													name: "OrderByItem",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "OrderByItem",
			pos:  position{line: 59, col: 1, offset: 1880},
			expr: &actionExpr{
				pos: position{line: 59, col: 16, offset: 1895},
				run: (*parser).callonOrderByItem1,
				expr: &seqExpr{
					pos: position{line: 59, col: 16, offset: 1895},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 59, col: 16, offset: 1895},
							label: "idx",
							expr: &ruleRefExpr{
								pos:  position{line: 59, col: 20, offset: 1899},
								name: "Integer",
							},
						},
						&labeledExpr{
							pos:   position{line: 59, col: 28, offset: 1907},
							label: "dir",
							expr: &zeroOrOneExpr{
								pos: position{line: 59, col: 32, offset: 1911},
								expr: &actionExpr{
									pos: position{line: 59, col: 34, offset: 1913},
									run: (*parser).callonOrderByItem7,
									expr: &seqExpr{
										pos: position{line: 59, col: 34, offset: 1913},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 59, col: 34, offset: 1913},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 59, col: 36, offset: 1915},
												label: "d",
												expr: &choiceExpr{
													pos: position{line: 59, col: 39, offset: 1918},
													alternatives: []any{
														&litMatcher{
															pos:        position{line: 59, col: 39, offset: 1918},
															val:        "asc",
															ignoreCase: true,
															want:       "\"ASC\"i",
														},
														&litMatcher{
															pos:        position{line: 59, col: 48, offset: 1927},
															val:        "desc",
															ignoreCase: true,
															want:       "\"DESC\"i",
														},
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "LimitClause",
			pos:  position{line: 63, col: 1, offset: 2018},
			expr: &actionExpr{
				pos: position{line: 63, col: 16, offset: 2033},
				run: (*parser).callonLimitClause1,
				expr: &seqExpr{
					pos: position{line: 63, col: 16, offset: 2033},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 63, col: 16, offset: 2033},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 63, col: 18, offset: 2035},
							val:        "limit",
							ignoreCase: true,
							want:       "\"LIMIT\"i",
						},
						&ruleRefExpr{
							pos:  position{line: 63, col: 27, offset: 2044},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 63, col: 29, offset: 2046},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 63, col: 31, offset: 2048},
								name: "Integer",
							},
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 71, col: 1, offset: 2309},
			expr: &ruleRefExpr{
				pos:  position{line: 71, col: 9, offset: 2317},
				name: "OrExpr",
			},
		},
		{
			name: "OrExpr",
			pos:  position{line: 73, col: 1, offset: 2325},
			expr: &actionExpr{
				pos: position{line: 73, col: 11, offset: 2335},
				run: (*parser).callonOrExpr1,
				expr: &seqExpr{
					pos: position{line: 73, col: 11, offset: 2335},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 73, col: 11, offset: 2335},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 73, col: 17, offset: 2341},
								name: "AndExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 73, col: 25, offset: 2349},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 73, col: 30, offset: 2354},
								expr: &actionExpr{
									pos: position{line: 73, col: 32, offset: 2356},
									run: (*parser).callonOrExpr7,
									expr: &seqExpr{
										pos: position{line: 73, col: 32, offset: 2356},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 73, col: 32, offset: 2356},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 73, col: 34, offset: 2358},
												val:        "or",
												ignoreCase: true,
												want:       "\"OR\"i",
											},
											&notExpr{
												pos: position{line: 73, col: 40, offset: 2364},
												expr: &charClassMatcher{
													pos:        position{line: 73, col: 41, offset: 2365},
													val:        "[a-zA-Z0-9_]",
													chars:      []rune{'_'},
													ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
													ignoreCase: false,
													inverted:   false,
												},
											},
											&ruleRefExpr{
												pos:  position{line: 73, col: 54, offset: 2378},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 73, col: 56, offset: 2380},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 73, col: 58, offset: 2382},
													name: "AndExpr",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AndExpr",
			pos:  position{line: 77, col: 1, offset: 2468},
			expr: &actionExpr{
				pos: position{line: 77, col: 12, offset: 2479},
				run: (*parser).callonAndExpr1,
				expr: &seqExpr{
					pos: position{line: 77, col: 12, offset: 2479},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 77, col: 12, offset: 2479},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 77, col: 18, offset: 2485},
								name: "Comparison",
							},
						},
						&labeledExpr{
							pos:   position{line: 77, col: 29, offset: 2496},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 77, col: 34, offset: 2501},
								expr: &actionExpr{
									pos: position{line: 77, col: 36, offset: 2503},
									run: (*parser).callonAndExpr7,
									expr: &seqExpr{
										pos: position{line: 77, col: 36, offset: 2503},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 77, col: 36, offset: 2503},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 77, col: 38, offset: 2505},
												val:        "and",
												ignoreCase: true,
												want:       "\"AND\"i",
											},
											&notExpr{
												pos: position{line: 77, col: 45, offset: 2512},
												expr: &charClassMatcher{
													pos:        position{line: 77, col: 46, offset: 2513},
													val:        "[a-zA-Z0-9_]",
													chars:      []rune{'_'},
													ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
													ignoreCase: false,
													inverted:   false,
												},
											},
											&ruleRefExpr{
												pos:  position{line: 77, col: 59, offset: 2526},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 77, col: 61, offset: 2528},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 77, col: 63, offset: 2530},
													name: "Comparison",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Comparison",
			pos:  position{line: 81, col: 1, offset: 2620},
			expr: &actionExpr{
				pos: position{line: 81, col: 15, offset: 2634},
				run: (*parser).callonComparison1,
				expr: &seqExpr{
					pos: position{line: 81, col: 15, offset: 2634},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 81, col: 15, offset: 2634},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 81, col: 20, offset: 2639},
								name: "Additive",
							},
						},
						&labeledExpr{
							pos:   position{line: 81, col: 29, offset: 2648},
							label: "op",
							expr: &zeroOrOneExpr{
								pos: position{line: 81, col: 32, offset: 2651},
								expr: &ruleRefExpr{
									pos:  position{line: 81, col: 32, offset: 2651},
									name: "CompOp",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 81, col: 40, offset: 2659},
							label: "right",
							expr: &zeroOrOneExpr{
								pos: position{line: 81, col: 46, offset: 2665},
								expr: &ruleRefExpr{
									pos:  position{line: 81, col: 46, offset: 2665},
									name: "Additive",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CompOp",
			pos:  position{line: 85, col: 1, offset: 2729},
			expr: &actionExpr{
				pos: position{line: 85, col: 11, offset: 2739},
				run: (*parser).callonCompOp1,
				expr: &seqExpr{
					pos: position{line: 85, col: 11, offset: 2739},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 85, col: 11, offset: 2739},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 85, col: 13, offset: 2741},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 85, col: 18, offset: 2746},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 85, col: 18, offset: 2746},
										val:        "<=",
										ignoreCase: false,
										want:       "\"<=\"",
									},
									&litMatcher{
										pos:        position{line: 85, col: 25, offset: 2753},
										val:        ">=",
										ignoreCase: false,
										want:       "\">=\"",
									},
									&litMatcher{
										pos:        position{line: 85, col: 32, offset: 2760},
										val:        "<>",
										ignoreCase: false,
										want:       "\"<>\"",
									},
									&litMatcher{
										pos:        position{line: 85, col: 39, offset: 2767},
										val:        "!=",
										ignoreCase: false,
										want:       "\"!=\"",
									},
									&litMatcher{
										pos:        position{line: 85, col: 46, offset: 2774},
										val:        "<",
										ignoreCase: false,
										want:       "\"<\"",
									},
									&litMatcher{
										pos:        position{line: 85, col: 52, offset: 2780},
										val:        ">",
										ignoreCase: false,
										want:       "\">\"",
									},
									&litMatcher{
										pos:        position{line: 85, col: 58, offset: 2786},
										val:        "=",
										ignoreCase: false,
										want:       "\"=\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 85, col: 64, offset: 2792},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Additive",
			pos:  position{line: 89, col: 1, offset: 2830},
			expr: &actionExpr{
				pos: position{line: 89, col: 13, offset: 2842},
				run: (*parser).callonAdditive1,
				expr: &seqExpr{
					pos: position{line: 89, col: 13, offset: 2842},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 89, col: 13, offset: 2842},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 89, col: 19, offset: 2848},
								name: "Multiplicative",
							},
						},
						&labeledExpr{
							pos:   position{line: 89, col: 34, offset: 2863},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 89, col: 39, offset: 2868},
								expr: &actionExpr{
									pos: position{line: 89, col: 41, offset: 2870},
									run: (*parser).callonAdditive7,
									expr: &seqExpr{
										pos: position{line: 89, col: 41, offset: 2870},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 89, col: 41, offset: 2870},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 89, col: 43, offset: 2872},
												label: "op",
												expr: &ruleRefExpr{
													pos:  position{line: 89, col: 46, offset: 2875},
													name: "AddOp",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 89, col: 52, offset: 2881},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 89, col: 54, offset: 2883},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 89, col: 56, offset: 2885},
													name: "Multiplicative",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AddOp",
			pos:  position{line: 93, col: 1, offset: 2993},
			expr: &actionExpr{
				pos: position{line: 93, col: 10, offset: 3002},
				run: (*parser).callonAddOp1,
				expr: &labeledExpr{
					pos:   position{line: 93, col: 10, offset: 3002},
					label: "op",
					expr: &choiceExpr{
						pos: position{line: 93, col: 15, offset: 3007},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 93, col: 15, offset: 3007},
								val:        "+",
								ignoreCase: false,
								want:       "\"+\"",
							},
							&litMatcher{
								pos:        position{line: 93, col: 21, offset: 3013},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
					},
				},
			},
		},
		{
			name: "Multiplicative",
			pos:  position{line: 97, col: 1, offset: 3055},
			expr: &actionExpr{
				pos: position{line: 97, col: 19, offset: 3073},
				run: (*parser).callonMultiplicative1,
				expr: &seqExpr{
					pos: position{line: 97, col: 19, offset: 3073},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 97, col: 19, offset: 3073},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 97, col: 25, offset: 3079},
								name: "Unary",
							},
						},
						&labeledExpr{
							pos:   position{line: 97, col: 31, offset: 3085},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 97, col: 36, offset: 3090},
								expr: &actionExpr{
									pos: position{line: 97, col: 38, offset: 3092},
									run: (*parser).callonMultiplicative7,
									expr: &seqExpr{
										pos: position{line: 97, col: 38, offset: 3092},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 97, col: 38, offset: 3092},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 97, col: 40, offset: 3094},
												label: "op",
												expr: &ruleRefExpr{
													pos:  position{line: 97, col: 43, offset: 3097},
													name: "MulOp",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 97, col: 49, offset: 3103},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 97, col: 51, offset: 3105},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 97, col: 53, offset: 3107},
													name: "Unary",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "MulOp",
			pos:  position{line: 101, col: 1, offset: 3212},
			expr: &actionExpr{
				pos: position{line: 101, col: 10, offset: 3221},
				run: (*parser).callonMulOp1,
				expr: &labeledExpr{
					pos:   position{line: 101, col: 10, offset: 3221},
					label: "op",
					expr: &choiceExpr{
						pos: position{line: 101, col: 15, offset: 3226},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 101, col: 15, offset: 3226},
								val:        "*",
								ignoreCase: false,
								want:       "\"*\"",
							},
							&litMatcher{
								pos:        position{line: 101, col: 21, offset: 3232},
								val:        "/",
								ignoreCase: false,
								want:       "\"/\"",
							},
						},
					},
				},
			},
		},
		{
			name: "Unary",
			pos:  position{line: 105, col: 1, offset: 3274},
			expr: &actionExpr{
				pos: position{line: 105, col: 10, offset: 3283},
				run: (*parser).callonUnary1,
				expr: &seqExpr{
					pos: position{line: 105, col: 10, offset: 3283},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 105, col: 10, offset: 3283},
							label: "op",
							expr: &zeroOrOneExpr{
								pos: position{line: 105, col: 13, offset: 3286},
								expr: &ruleRefExpr{
									pos:  position{line: 105, col: 13, offset: 3286},
									name: "UnaryOp",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 105, col: 22, offset: 3295},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 105, col: 24, offset: 3297},
							label: "primary",
							expr: &ruleRefExpr{
								pos:  position{line: 105, col: 32, offset: 3305},
								name: "Primary",
							},
						},
					},
				},
			},
		},
		{
			name: "UnaryOp",
			pos:  position{line: 109, col: 1, offset: 3358},
			expr: &actionExpr{
				pos: position{line: 109, col: 12, offset: 3369},
				run: (*parser).callonUnaryOp1,
				expr: &seqExpr{
					pos: position{line: 109, col: 12, offset: 3369},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 109, col: 12, offset: 3369},
							label: "op",
							expr: &choiceExpr{
								pos: position{line: 109, col: 17, offset: 3374},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 109, col: 17, offset: 3374},
										val:        "not",
										ignoreCase: true,
										want:       "\"NOT\"i",
									},
									&litMatcher{
										pos:        position{line: 109, col: 26, offset: 3383},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 109, col: 32, offset: 3389},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Primary",
			pos:  position{line: 117, col: 1, offset: 3611},
			expr: &choiceExpr{
				pos: position{line: 117, col: 12, offset: 3622},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 117, col: 12, offset: 3622},
						name: "Literal",
					},
					&ruleRefExpr{
						pos:  position{line: 117, col: 22, offset: 3632},
						name: "FunctionCall",
					},
					&ruleRefExpr{
						pos:  position{line: 117, col: 37, offset: 3647},
						name: "ColumnRef",
					},
					&ruleRefExpr{
						pos:  position{line: 117, col: 49, offset: 3659},
						name: "ParenExpr",
					},
				},
			},
		},
		{
			name: "ParenExpr",
			pos:  position{line: 119, col: 1, offset: 3670},
			expr: &actionExpr{
				pos: position{line: 119, col: 14, offset: 3683},
				run: (*parser).callonParenExpr1,
				expr: &seqExpr{
					pos: position{line: 119, col: 14, offset: 3683},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 119, col: 14, offset: 3683},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 119, col: 18, offset: 3687},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 119, col: 20, offset: 3689},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 119, col: 25, offset: 3694},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 119, col: 30, offset: 3699},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 119, col: 32, offset: 3701},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "Literal",
			pos:  position{line: 123, col: 1, offset: 3731},
			expr: &choiceExpr{
				pos: position{line: 123, col: 12, offset: 3742},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 123, col: 12, offset: 3742},
						name: "BoolLiteral",
					},
					&ruleRefExpr{
						pos:  position{line: 123, col: 26, offset: 3756},
						name: "StringLiteral",
					},
					&ruleRefExpr{
						pos:  position{line: 123, col: 42, offset: 3772},
						name: "IntLiteral",
					},
				},
			},
		},
		{
			name: "IntLiteral",
			pos:  position{line: 125, col: 1, offset: 3784},
			expr: &actionExpr{
				pos: position{line: 125, col: 15, offset: 3798},
				run: (*parser).callonIntLiteral1,
				expr: &oneOrMoreExpr{
					pos: position{line: 125, col: 15, offset: 3798},
					expr: &charClassMatcher{
						pos:        position{line: 125, col: 15, offset: 3798},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "StringLiteral",
			pos:  position{line: 129, col: 1, offset: 3858},
			expr: &actionExpr{
				pos: position{line: 129, col: 18, offset: 3875},
				run: (*parser).callonStringLiteral1,
				expr: &seqExpr{
					pos: position{line: 129, col: 18, offset: 3875},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 129, col: 18, offset: 3875},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
						&labeledExpr{
							pos:   position{line: 129, col: 23, offset: 3880},
							label: "content",
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 31, offset: 3888},
								name: "StringContent",
							},
						},
						&litMatcher{
							pos:        position{line: 129, col: 45, offset: 3902},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
					},
				},
			},
		},
		{
			name: "StringContent",
			pos:  position{line: 133, col: 1, offset: 3956},
			expr: &actionExpr{
				pos: position{line: 133, col: 18, offset: 3973},
				run: (*parser).callonStringContent1,
				expr: &zeroOrMoreExpr{
					pos: position{line: 133, col: 18, offset: 3973},
					expr: &choiceExpr{
						pos: position{line: 133, col: 20, offset: 3975},
						alternatives: []any{
							&seqExpr{
								pos: position{line: 133, col: 20, offset: 3975},
								exprs: []any{
									&notExpr{
										pos: position{line: 133, col: 20, offset: 3975},
										expr: &litMatcher{
											pos:        position{line: 133, col: 21, offset: 3976},
											val:        "'",
											ignoreCase: false,
											want:       "\"'\"",
										},
									},
									&anyMatcher{
										line: 133, col: 26, offset: 3981,
									},
								},
							},
							&litMatcher{
								pos:        position{line: 133, col: 30, offset: 3985},
								val:        "''",
								ignoreCase: false,
								want:       "\"''\"",
							},
						},
					},
				},
			},
		},
		{
			name: "BoolLiteral",
			pos:  position{line: 137, col: 1, offset: 4029},
			expr: &actionExpr{
				pos: position{line: 137, col: 16, offset: 4044},
				run: (*parser).callonBoolLiteral1,
				expr: &choiceExpr{
					pos: position{line: 137, col: 18, offset: 4046},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 137, col: 18, offset: 4046},
							val:        "true",
							ignoreCase: true,
							want:       "\"TRUE\"i",
						},
						&litMatcher{
							pos:        position{line: 137, col: 28, offset: 4056},
							val:        "false",
							ignoreCase: true,
							want:       "\"FALSE\"i",
						},
					},
				},
			},
		},
		{
			name: "FunctionCall",
			pos:  position{line: 141, col: 1, offset: 4121},
			expr: &actionExpr{
				pos: position{line: 141, col: 17, offset: 4137},
				run: (*parser).callonFunctionCall1,
				expr: &seqExpr{
					pos: position{line: 141, col: 17, offset: 4137},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 141, col: 17, offset: 4137},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 141, col: 22, offset: 4142},
								name: "FunctionName",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 141, col: 35, offset: 4155},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 141, col: 37, offset: 4157},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 141, col: 41, offset: 4161},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 141, col: 43, offset: 4163},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 141, col: 48, offset: 4168},
								expr: &ruleRefExpr{
									pos:  position{line: 141, col: 48, offset: 4168},
									name: "FunctionArgs",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 141, col: 62, offset: 4182},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 141, col: 64, offset: 4184},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "FunctionName",
			pos:  position{line: 145, col: 1, offset: 4235},
			expr: &actionExpr{
				pos: position{line: 145, col: 17, offset: 4251},
				run: (*parser).callonFunctionName1,
				expr: &choiceExpr{
					pos: position{line: 145, col: 19, offset: 4253},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 145, col: 19, offset: 4253},
							val:        "strlen",
							ignoreCase: true,
							want:       "\"STRLEN\"i",
						},
						&litMatcher{
							pos:        position{line: 145, col: 31, offset: 4265},
							val:        "concat",
							ignoreCase: true,
							want:       "\"CONCAT\"i",
						},
						&litMatcher{
							pos:        position{line: 145, col: 43, offset: 4277},
							val:        "upper",
							ignoreCase: true,
							want:       "\"UPPER\"i",
						},
						&litMatcher{
							pos:        position{line: 145, col: 54, offset: 4288},
							val:        "lower",
							ignoreCase: true,
							want:       "\"LOWER\"i",
						},
					},
				},
			},
		},
		{
			name: "FunctionArgs",
			pos:  position{line: 149, col: 1, offset: 4335},
			expr: &actionExpr{
				pos: position{line: 149, col: 17, offset: 4351},
				run: (*parser).callonFunctionArgs1,
				expr: &seqExpr{
					pos: position{line: 149, col: 17, offset: 4351},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 149, col: 17, offset: 4351},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 149, col: 23, offset: 4357},
								name: "Expr",
							},
						},
						&labeledExpr{
							pos:   position{line: 149, col: 28, offset: 4362},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 149, col: 33, offset: 4367},
								expr: &actionExpr{
									pos: position{line: 149, col: 35, offset: 4369},
									run: (*parser).callonFunctionArgs7,
									expr: &seqExpr{
										pos: position{line: 149, col: 35, offset: 4369},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 149, col: 35, offset: 4369},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 149, col: 37, offset: 4371},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
											&ruleRefExpr{
												pos:  position{line: 149, col: 41, offset: 4375},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 149, col: 43, offset: 4377},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 149, col: 45, offset: 4379},
													name: "Expr",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ColumnRef",
			pos:  position{line: 153, col: 1, offset: 4453},
			expr: &actionExpr{
				pos: position{line: 153, col: 14, offset: 4466},
				run: (*parser).callonColumnRef1,
				expr: &seqExpr{
					pos: position{line: 153, col: 14, offset: 4466},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 153, col: 14, offset: 4466},
							label: "table",
							expr: &zeroOrOneExpr{
								pos: position{line: 153, col: 20, offset: 4472},
								expr: &actionExpr{
									pos: position{line: 153, col: 22, offset: 4474},
									run: (*parser).callonColumnRef5,
									expr: &seqExpr{
										pos: position{line: 153, col: 22, offset: 4474},
										exprs: []any{
											&labeledExpr{
												pos:   position{line: 153, col: 22, offset: 4474},
												label: "name",
												expr: &ruleRefExpr{
													pos:  position{line: 153, col: 27, offset: 4479},
													name: "Identifier",
												},
											},
											&litMatcher{
												pos:        position{line: 153, col: 38, offset: 4490},
												val:        ".",
												ignoreCase: false,
												want:       "\".\"",
											},
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 153, col: 66, offset: 4518},
							label: "column",
							expr: &ruleRefExpr{
								pos:  position{line: 153, col: 73, offset: 4525},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 161, col: 1, offset: 4768},
			expr: &actionExpr{
				pos: position{line: 161, col: 15, offset: 4782},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 161, col: 15, offset: 4782},
					exprs: []any{
						&notExpr{
							pos: position{line: 161, col: 15, offset: 4782},
							expr: &ruleRefExpr{
								pos:  position{line: 161, col: 16, offset: 4783},
								name: "ReservedWord",
							},
						},
						&charClassMatcher{
							pos:        position{line: 161, col: 29, offset: 4796},
							val:        "[a-zA-Z_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 161, col: 39, offset: 4806},
							expr: &charClassMatcher{
								pos:        position{line: 161, col: 39, offset: 4806},
								val:        "[a-zA-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "ReservedWord",
			pos:  position{line: 165, col: 1, offset: 4856},
			expr: &seqExpr{
				pos: position{line: 165, col: 17, offset: 4872},
				exprs: []any{
					&choiceExpr{
						pos: position{line: 165, col: 19, offset: 4874},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 165, col: 19, offset: 4874},
								val:        "select",
								ignoreCase: true,
								want:       "\"SELECT\"i",
							},
							&litMatcher{
								pos:        position{line: 165, col: 31, offset: 4886},
								val:        "from",
								ignoreCase: true,
								want:       "\"FROM\"i",
							},
							&litMatcher{
								pos:        position{line: 165, col: 41, offset: 4896},
								val:        "where",
								ignoreCase: true,
								want:       "\"WHERE\"i",
							},
							&litMatcher{
								pos:        position{line: 165, col: 52, offset: 4907},
								val:        "order",
								ignoreCase: true,
								want:       "\"ORDER\"i",
							},
							&litMatcher{
								pos:        position{line: 165, col: 63, offset: 4918},
								val:        "by",
								ignoreCase: true,
								want:       "\"BY\"i",
							},
							&litMatcher{
								pos:        position{line: 165, col: 71, offset: 4926},
								val:        "asc",
								ignoreCase: true,
								want:       "\"ASC\"i",
							},
							&litMatcher{
								pos:        position{line: 165, col: 80, offset: 4935},
								val:        "desc",
								ignoreCase: true,
								want:       "\"DESC\"i",
							},
							&litMatcher{
								pos:        position{line: 166, col: 18, offset: 4963},
								val:        "limit",
								ignoreCase: true,
								want:       "\"LIMIT\"i",
							},
							&litMatcher{
								pos:        position{line: 166, col: 29, offset: 4974},
								val:        "and",
								ignoreCase: true,
								want:       "\"AND\"i",
							},
							&litMatcher{
								pos:        position{line: 166, col: 38, offset: 4983},
								val:        "or",
								ignoreCase: true,
								want:       "\"OR\"i",
							},
							&litMatcher{
								pos:        position{line: 166, col: 46, offset: 4991},
								val:        "not",
								ignoreCase: true,
								want:       "\"NOT\"i",
							},
							&litMatcher{
								pos:        position{line: 166, col: 55, offset: 5000},
								val:        "true",
								ignoreCase: true,
								want:       "\"TRUE\"i",
							},
							&litMatcher{
								pos:        position{line: 166, col: 65, offset: 5010},
								val:        "false",
								ignoreCase: true,
								want:       "\"FALSE\"i",
							},
							&litMatcher{
								pos:        position{line: 167, col: 18, offset: 5038},
								val:        "strlen",
								ignoreCase: true,
								want:       "\"STRLEN\"i",
							},
							&litMatcher{
								pos:        position{line: 167, col: 30, offset: 5050},
								val:        "concat",
								ignoreCase: true,
								want:       "\"CONCAT\"i",
							},
							&litMatcher{
								pos:        position{line: 167, col: 42, offset: 5062},
								val:        "upper",
								ignoreCase: true,
								want:       "\"UPPER\"i",
							},
							&litMatcher{
								pos:        position{line: 167, col: 53, offset: 5073},
								val:        "lower",
								ignoreCase: true,
								want:       "\"LOWER\"i",
							},
						},
					},
					&notExpr{
						pos: position{line: 167, col: 64, offset: 5084},
						expr: &charClassMatcher{
							pos:        position{line: 167, col: 65, offset: 5085},
							val:        "[a-zA-Z0-9_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 169, col: 1, offset: 5099},
			expr: &actionExpr{
				pos: position{line: 169, col: 12, offset: 5110},
				run: (*parser).callonInteger1,
				expr: &oneOrMoreExpr{
					pos: position{line: 169, col: 12, offset: 5110},
					expr: &charClassMatcher{
						pos:        position{line: 169, col: 12, offset: 5110},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 173, col: 1, offset: 5163},
			expr: &zeroOrMoreExpr{
				pos: position{line: 173, col: 19, offset: 5181},
				expr: &charClassMatcher{
					pos:        position{line: 173, col: 19, offset: 5181},
					val:        "[ \\t\\n\\r]",
					chars:      []rune{' ', '\t', '\n', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 175, col: 1, offset: 5193},
			expr: &notExpr{
				pos: position{line: 175, col: 8, offset: 5200},
				expr: &anyMatcher{
					line: 175, col: 9, offset: 5201,
				},
			},
		},
	},
}

func (c *current) onQuery1(columns, from, where, orderBy, limit any) (any, error) {
	return buildQuery(columns, from, where, orderBy, limit), nil
}

func (p *parser) callonQuery1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQuery1(stack["columns"], stack["from"], stack["where"], stack["orderBy"], stack["limit"])
}

func (c *current) onColumnList7(e any) (any, error) {
	return e, nil
}

func (p *parser) callonColumnList7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onColumnList7(stack["e"])
}

func (c *current) onColumnList1(first, rest any) (any, error) {
	return buildColumnList(first, rest), nil
}

func (p *parser) callonColumnList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onColumnList1(stack["first"], stack["rest"])
}

func (c *current) onFromClause10(name any) (any, error) {
	return name, nil
}

func (p *parser) callonFromClause10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFromClause10(stack["name"])
}

func (c *current) onFromClause1(first, rest any) (any, error) {
	s := first.(string)
	return &s, nil
}

func (p *parser) callonFromClause1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFromClause1(stack["first"], stack["rest"])
}

func (c *current) onWhereClause1(expr any) (any, error) {
	return expr, nil
}

func (p *parser) callonWhereClause1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWhereClause1(stack["expr"])
}

func (c *current) onOrderByClause12(o any) (any, error) {
	return o, nil
}

func (p *parser) callonOrderByClause12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrderByClause12(stack["o"])
}

func (c *current) onOrderByClause1(first, rest any) (any, error) {
	return buildOrderByList(first, rest), nil
}

func (p *parser) callonOrderByClause1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrderByClause1(stack["first"], stack["rest"])
}

func (c *current) onOrderByItem7(d any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonOrderByItem7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrderByItem7(stack["d"])
}

func (c *current) onOrderByItem1(idx, dir any) (any, error) {
	return buildOrderByItem(idx, dir), nil
}

func (p *parser) callonOrderByItem1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrderByItem1(stack["idx"], stack["dir"])
}

func (c *current) onLimitClause1(n any) (any, error) {
	return buildLimitClause(n), nil
}

func (p *parser) callonLimitClause1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLimitClause1(stack["n"])
}

func (c *current) onOrExpr7(e any) (any, error) {
	return e, nil
}

func (p *parser) callonOrExpr7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrExpr7(stack["e"])
}

func (c *current) onOrExpr1(first, rest any) (any, error) {
	return buildBinaryChain(first, rest, "OR"), nil
}

func (p *parser) callonOrExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrExpr1(stack["first"], stack["rest"])
}

func (c *current) onAndExpr7(e any) (any, error) {
	return e, nil
}

func (p *parser) callonAndExpr7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndExpr7(stack["e"])
}

func (c *current) onAndExpr1(first, rest any) (any, error) {
	return buildBinaryChain(first, rest, "AND"), nil
}

func (p *parser) callonAndExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndExpr1(stack["first"], stack["rest"])
}

func (c *current) onComparison1(left, op, right any) (any, error) {
	return buildComparison(left, op, right), nil
}

func (p *parser) callonComparison1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComparison1(stack["left"], stack["op"], stack["right"])
}

func (c *current) onCompOp1(op any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonCompOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCompOp1(stack["op"])
}

func (c *current) onAdditive7(op, e any) (any, error) {
	return []interface{}{op, e}, nil
}

func (p *parser) callonAdditive7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdditive7(stack["op"], stack["e"])
}

func (c *current) onAdditive1(first, rest any) (any, error) {
	return buildAdditiveChain(first, rest), nil
}

func (p *parser) callonAdditive1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAdditive1(stack["first"], stack["rest"])
}

func (c *current) onAddOp1(op any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonAddOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAddOp1(stack["op"])
}

func (c *current) onMultiplicative7(op, e any) (any, error) {
	return []interface{}{op, e}, nil
}

func (p *parser) callonMultiplicative7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicative7(stack["op"], stack["e"])
}

func (c *current) onMultiplicative1(first, rest any) (any, error) {
	return buildMultiplicativeChain(first, rest), nil
}

func (p *parser) callonMultiplicative1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiplicative1(stack["first"], stack["rest"])
}

func (c *current) onMulOp1(op any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonMulOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMulOp1(stack["op"])
}

func (c *current) onUnary1(op, primary any) (any, error) {
	return buildUnary(op, primary), nil
}

func (p *parser) callonUnary1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnary1(stack["op"], stack["primary"])
}

func (c *current) onUnaryOp1(op any) (any, error) {
	return string(c.text), nil
}

func (p *parser) callonUnaryOp1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnaryOp1(stack["op"])
}

func (c *current) onParenExpr1(expr any) (any, error) {
	return expr, nil
}

func (p *parser) callonParenExpr1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParenExpr1(stack["expr"])
}

func (c *current) onIntLiteral1() (any, error) {
	return buildIntLiteral(string(c.text)), nil
}

func (p *parser) callonIntLiteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntLiteral1()
}

func (c *current) onStringLiteral1(content any) (any, error) {
	return buildStringLiteral(content), nil
}

func (p *parser) callonStringLiteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringLiteral1(stack["content"])
}

func (c *current) onStringContent1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonStringContent1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStringContent1()
}

func (c *current) onBoolLiteral1() (any, error) {
	return buildBoolLiteral(string(c.text)), nil
}

func (p *parser) callonBoolLiteral1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolLiteral1()
}

func (c *current) onFunctionCall1(name, args any) (any, error) {
	return buildFunction(name, args), nil
}

func (p *parser) callonFunctionCall1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionCall1(stack["name"], stack["args"])
}

func (c *current) onFunctionName1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonFunctionName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionName1()
}

func (c *current) onFunctionArgs7(e any) (any, error) {
	return e, nil
}

func (p *parser) callonFunctionArgs7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionArgs7(stack["e"])
}

func (c *current) onFunctionArgs1(first, rest any) (any, error) {
	return buildArgsList(first, rest), nil
}

func (p *parser) callonFunctionArgs1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionArgs1(stack["first"], stack["rest"])
}

func (c *current) onColumnRef5(name any) (any, error) {
	return name, nil
}

func (p *parser) callonColumnRef5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onColumnRef5(stack["name"])
}

func (c *current) onColumnRef1(table, column any) (any, error) {
	return buildColumnRef(table, column), nil
}

func (p *parser) callonColumnRef1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onColumnRef1(stack["table"], stack["column"])
}

func (c *current) onIdentifier1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonIdentifier1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onInteger1() (any, error) {
	return parseInt(string(c.text)), nil
}

func (p *parser) callonInteger1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
