/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SystemInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemInformation{}

// SystemInformation Basic information about the system
type SystemInformation struct {
	// Version of the DBMS interface
	InterfaceVersion *string `json:"interfaceVersion,omitempty"`
	// Version of the DBMS system
	Version string `json:"version"`
	// Author of the DBMS system (will help me to automate testing)
	Author string `json:"author"`
	// System uptime in seconds
	Uptime *int64 `json:"uptime,omitempty"`
}

type _SystemInformation SystemInformation

// NewSystemInformation instantiates a new SystemInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemInformation(version string, author string) *SystemInformation {
	this := SystemInformation{}
	this.Version = version
	this.Author = author
	return &this
}

// NewSystemInformationWithDefaults instantiates a new SystemInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemInformationWithDefaults() *SystemInformation {
	this := SystemInformation{}
	return &this
}

// GetInterfaceVersion returns the InterfaceVersion field value if set, zero value otherwise.
func (o *SystemInformation) GetInterfaceVersion() string {
	if o == nil || IsNil(o.InterfaceVersion) {
		var ret string
		return ret
	}
	return *o.InterfaceVersion
}

// GetInterfaceVersionOk returns a tuple with the InterfaceVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInformation) GetInterfaceVersionOk() (*string, bool) {
	if o == nil || IsNil(o.InterfaceVersion) {
		return nil, false
	}
	return o.InterfaceVersion, true
}

// HasInterfaceVersion returns a boolean if a field has been set.
func (o *SystemInformation) HasInterfaceVersion() bool {
	if o != nil && !IsNil(o.InterfaceVersion) {
		return true
	}

	return false
}

// SetInterfaceVersion gets a reference to the given string and assigns it to the InterfaceVersion field.
func (o *SystemInformation) SetInterfaceVersion(v string) {
	o.InterfaceVersion = &v
}

// GetVersion returns the Version field value
func (o *SystemInformation) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *SystemInformation) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *SystemInformation) SetVersion(v string) {
	o.Version = v
}

// GetAuthor returns the Author field value
func (o *SystemInformation) GetAuthor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Author
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
func (o *SystemInformation) GetAuthorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Author, true
}

// SetAuthor sets field value
func (o *SystemInformation) SetAuthor(v string) {
	o.Author = v
}

// GetUptime returns the Uptime field value if set, zero value otherwise.
func (o *SystemInformation) GetUptime() int64 {
	if o == nil || IsNil(o.Uptime) {
		var ret int64
		return ret
	}
	return *o.Uptime
}

// GetUptimeOk returns a tuple with the Uptime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemInformation) GetUptimeOk() (*int64, bool) {
	if o == nil || IsNil(o.Uptime) {
		return nil, false
	}
	return o.Uptime, true
}

// HasUptime returns a boolean if a field has been set.
func (o *SystemInformation) HasUptime() bool {
	if o != nil && !IsNil(o.Uptime) {
		return true
	}

	return false
}

// SetUptime gets a reference to the given int64 and assigns it to the Uptime field.
func (o *SystemInformation) SetUptime(v int64) {
	o.Uptime = &v
}

func (o SystemInformation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InterfaceVersion) {
		toSerialize["interfaceVersion"] = o.InterfaceVersion
	}
	toSerialize["version"] = o.Version
	toSerialize["author"] = o.Author
	if !IsNil(o.Uptime) {
		toSerialize["uptime"] = o.Uptime
	}
	return toSerialize, nil
}

func (o *SystemInformation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
		"author",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemInformation := _SystemInformation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemInformation)

	if err != nil {
		return err
	}

	*o = SystemInformation(varSystemInformation)

	return err
}

type NullableSystemInformation struct {
	value *SystemInformation
	isSet bool
}

func (v NullableSystemInformation) Get() *SystemInformation {
	return v.value
}

func (v *NullableSystemInformation) Set(val *SystemInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemInformation(val *SystemInformation) *NullableSystemInformation {
	return &NullableSystemInformation{value: val, isSet: true}
}

func (v NullableSystemInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


