/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ShallowTable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShallowTable{}

// ShallowTable Description of a shallow representation of a table (e.g. without detailed column information)
type ShallowTable struct {
	// ID of selected Table (I propose UUID, but it is under your own discretion)
	TableId *string `json:"tableId,omitempty"`
	Name string `json:"name"`
}

type _ShallowTable ShallowTable

// NewShallowTable instantiates a new ShallowTable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShallowTable(name string) *ShallowTable {
	this := ShallowTable{}
	this.Name = name
	return &this
}

// NewShallowTableWithDefaults instantiates a new ShallowTable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShallowTableWithDefaults() *ShallowTable {
	this := ShallowTable{}
	return &this
}

// GetTableId returns the TableId field value if set, zero value otherwise.
func (o *ShallowTable) GetTableId() string {
	if o == nil || IsNil(o.TableId) {
		var ret string
		return ret
	}
	return *o.TableId
}

// GetTableIdOk returns a tuple with the TableId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShallowTable) GetTableIdOk() (*string, bool) {
	if o == nil || IsNil(o.TableId) {
		return nil, false
	}
	return o.TableId, true
}

// HasTableId returns a boolean if a field has been set.
func (o *ShallowTable) HasTableId() bool {
	if o != nil && !IsNil(o.TableId) {
		return true
	}

	return false
}

// SetTableId gets a reference to the given string and assigns it to the TableId field.
func (o *ShallowTable) SetTableId(v string) {
	o.TableId = &v
}

// GetName returns the Name field value
func (o *ShallowTable) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ShallowTable) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ShallowTable) SetName(v string) {
	o.Name = v
}

func (o ShallowTable) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShallowTable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TableId) {
		toSerialize["tableId"] = o.TableId
	}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *ShallowTable) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShallowTable := _ShallowTable{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShallowTable)

	if err != nil {
		return err
	}

	*o = ShallowTable(varShallowTable)

	return err
}

type NullableShallowTable struct {
	value *ShallowTable
	isSet bool
}

func (v NullableShallowTable) Get() *ShallowTable {
	return v.value
}

func (v *NullableShallowTable) Set(val *ShallowTable) {
	v.value = val
	v.isSet = true
}

func (v NullableShallowTable) IsSet() bool {
	return v.isSet
}

func (v *NullableShallowTable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShallowTable(val *ShallowTable) *NullableShallowTable {
	return &NullableShallowTable{value: val, isSet: true}
}

func (v NullableShallowTable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShallowTable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


