/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi1

import (
	"encoding/json"
)

// checks if the SelectQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SelectQuery{}

// SelectQuery Description of a select query (extension in project no 4)
type SelectQuery struct {
	TableName *string `json:"tableName,omitempty"`
}

// NewSelectQuery instantiates a new SelectQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSelectQuery() *SelectQuery {
	this := SelectQuery{}
	return &this
}

// NewSelectQueryWithDefaults instantiates a new SelectQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSelectQueryWithDefaults() *SelectQuery {
	this := SelectQuery{}
	return &this
}

// GetTableName returns the TableName field value if set, zero value otherwise.
func (o *SelectQuery) GetTableName() string {
	if o == nil || IsNil(o.TableName) {
		var ret string
		return ret
	}
	return *o.TableName
}

// GetTableNameOk returns a tuple with the TableName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelectQuery) GetTableNameOk() (*string, bool) {
	if o == nil || IsNil(o.TableName) {
		return nil, false
	}
	return o.TableName, true
}

// HasTableName returns a boolean if a field has been set.
func (o *SelectQuery) HasTableName() bool {
	if o != nil && !IsNil(o.TableName) {
		return true
	}

	return false
}

// SetTableName gets a reference to the given string and assigns it to the TableName field.
func (o *SelectQuery) SetTableName(v string) {
	o.TableName = &v
}

func (o SelectQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SelectQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TableName) {
		toSerialize["tableName"] = o.TableName
	}
	return toSerialize, nil
}

type NullableSelectQuery struct {
	value *SelectQuery
	isSet bool
}

func (v NullableSelectQuery) Get() *SelectQuery {
	return v.value
}

func (v *NullableSelectQuery) Set(val *SelectQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableSelectQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableSelectQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSelectQuery(val *SelectQuery) *NullableSelectQuery {
	return &NullableSelectQuery{value: val, isSet: true}
}

func (v NullableSelectQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSelectQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


