/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MultipleProblemsError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultipleProblemsError{}

// MultipleProblemsError Error containing multiple problems about request processing. Useful when processing complex requests where multiple problems can occur at the same time.
type MultipleProblemsError struct {
	Problems []MultipleProblemsErrorProblemsInner `json:"problems"`
}

type _MultipleProblemsError MultipleProblemsError

// NewMultipleProblemsError instantiates a new MultipleProblemsError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultipleProblemsError(problems []MultipleProblemsErrorProblemsInner) *MultipleProblemsError {
	this := MultipleProblemsError{}
	this.Problems = problems
	return &this
}

// NewMultipleProblemsErrorWithDefaults instantiates a new MultipleProblemsError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultipleProblemsErrorWithDefaults() *MultipleProblemsError {
	this := MultipleProblemsError{}
	return &this
}

// GetProblems returns the Problems field value
func (o *MultipleProblemsError) GetProblems() []MultipleProblemsErrorProblemsInner {
	if o == nil {
		var ret []MultipleProblemsErrorProblemsInner
		return ret
	}

	return o.Problems
}

// GetProblemsOk returns a tuple with the Problems field value
// and a boolean to check if the value has been set.
func (o *MultipleProblemsError) GetProblemsOk() ([]MultipleProblemsErrorProblemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Problems, true
}

// SetProblems sets field value
func (o *MultipleProblemsError) SetProblems(v []MultipleProblemsErrorProblemsInner) {
	o.Problems = v
}

func (o MultipleProblemsError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultipleProblemsError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["problems"] = o.Problems
	return toSerialize, nil
}

func (o *MultipleProblemsError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"problems",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMultipleProblemsError := _MultipleProblemsError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMultipleProblemsError)

	if err != nil {
		return err
	}

	*o = MultipleProblemsError(varMultipleProblemsError)

	return err
}

type NullableMultipleProblemsError struct {
	value *MultipleProblemsError
	isSet bool
}

func (v NullableMultipleProblemsError) Get() *MultipleProblemsError {
	return v.value
}

func (v *NullableMultipleProblemsError) Set(val *MultipleProblemsError) {
	v.value = val
	v.isSet = true
}

func (v NullableMultipleProblemsError) IsSet() bool {
	return v.isSet
}

func (v *NullableMultipleProblemsError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultipleProblemsError(val *MultipleProblemsError) *NullableMultipleProblemsError {
	return &NullableMultipleProblemsError{value: val, isSet: true}
}

func (v NullableMultipleProblemsError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultipleProblemsError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


