/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi2

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// QueryQueryDefinition - struct for QueryQueryDefinition
type QueryQueryDefinition struct {
	CopyQuery *CopyQuery
	SelectQuery *SelectQuery
}

// CopyQueryAsQueryQueryDefinition is a convenience function that returns CopyQuery wrapped in QueryQueryDefinition
func CopyQueryAsQueryQueryDefinition(v *CopyQuery) QueryQueryDefinition {
	return QueryQueryDefinition{
		CopyQuery: v,
	}
}

// SelectQueryAsQueryQueryDefinition is a convenience function that returns SelectQuery wrapped in QueryQueryDefinition
func SelectQueryAsQueryQueryDefinition(v *SelectQuery) QueryQueryDefinition {
	return QueryQueryDefinition{
		SelectQuery: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *QueryQueryDefinition) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CopyQuery
	err = newStrictDecoder(data).Decode(&dst.CopyQuery)
	if err == nil {
		jsonCopyQuery, _ := json.Marshal(dst.CopyQuery)
		if string(jsonCopyQuery) == "{}" { // empty struct
			dst.CopyQuery = nil
		} else {
			if err = validator.Validate(dst.CopyQuery); err != nil {
				dst.CopyQuery = nil
			} else {
				match++
			}
		}
	} else {
		dst.CopyQuery = nil
	}

	// try to unmarshal data into SelectQuery
	err = newStrictDecoder(data).Decode(&dst.SelectQuery)
	if err == nil {
		jsonSelectQuery, _ := json.Marshal(dst.SelectQuery)
		if string(jsonSelectQuery) == "{}" { // empty struct
			dst.SelectQuery = nil
		} else {
			if err = validator.Validate(dst.SelectQuery); err != nil {
				dst.SelectQuery = nil
			} else {
				match++
			}
		}
	} else {
		dst.SelectQuery = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CopyQuery = nil
		dst.SelectQuery = nil

		return fmt.Errorf("data matches more than one schema in oneOf(QueryQueryDefinition)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(QueryQueryDefinition)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src QueryQueryDefinition) MarshalJSON() ([]byte, error) {
	if src.CopyQuery != nil {
		return json.Marshal(&src.CopyQuery)
	}

	if src.SelectQuery != nil {
		return json.Marshal(&src.SelectQuery)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *QueryQueryDefinition) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CopyQuery != nil {
		return obj.CopyQuery
	}

	if obj.SelectQuery != nil {
		return obj.SelectQuery
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj QueryQueryDefinition) GetActualInstanceValue() (interface{}) {
	if obj.CopyQuery != nil {
		return *obj.CopyQuery
	}

	if obj.SelectQuery != nil {
		return *obj.SelectQuery
	}

	// all schemas are nil
	return nil
}

type NullableQueryQueryDefinition struct {
	value *QueryQueryDefinition
	isSet bool
}

func (v NullableQueryQueryDefinition) Get() *QueryQueryDefinition {
	return v.value
}

func (v *NullableQueryQueryDefinition) Set(val *QueryQueryDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryQueryDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryQueryDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryQueryDefinition(val *QueryQueryDefinition) *NullableQueryQueryDefinition {
	return &NullableQueryQueryDefinition{value: val, isSet: true}
}

func (v NullableQueryQueryDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryQueryDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


