/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi2

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ColumnExpression - Description of a single column expression in SELECT query
type ColumnExpression struct {
	ColumnReferenceExpression *ColumnReferenceExpression
	ColumnarBinaryOperation *ColumnarBinaryOperation
	ColumnarUnaryOperation *ColumnarUnaryOperation
	Function *Function
	Literal *Literal
}

// ColumnReferenceExpressionAsColumnExpression is a convenience function that returns ColumnReferenceExpression wrapped in ColumnExpression
func ColumnReferenceExpressionAsColumnExpression(v *ColumnReferenceExpression) ColumnExpression {
	return ColumnExpression{
		ColumnReferenceExpression: v,
	}
}

// ColumnarBinaryOperationAsColumnExpression is a convenience function that returns ColumnarBinaryOperation wrapped in ColumnExpression
func ColumnarBinaryOperationAsColumnExpression(v *ColumnarBinaryOperation) ColumnExpression {
	return ColumnExpression{
		ColumnarBinaryOperation: v,
	}
}

// ColumnarUnaryOperationAsColumnExpression is a convenience function that returns ColumnarUnaryOperation wrapped in ColumnExpression
func ColumnarUnaryOperationAsColumnExpression(v *ColumnarUnaryOperation) ColumnExpression {
	return ColumnExpression{
		ColumnarUnaryOperation: v,
	}
}

// FunctionAsColumnExpression is a convenience function that returns Function wrapped in ColumnExpression
func FunctionAsColumnExpression(v *Function) ColumnExpression {
	return ColumnExpression{
		Function: v,
	}
}

// LiteralAsColumnExpression is a convenience function that returns Literal wrapped in ColumnExpression
func LiteralAsColumnExpression(v *Literal) ColumnExpression {
	return ColumnExpression{
		Literal: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ColumnExpression) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ColumnReferenceExpression
	err = newStrictDecoder(data).Decode(&dst.ColumnReferenceExpression)
	if err == nil {
		jsonColumnReferenceExpression, _ := json.Marshal(dst.ColumnReferenceExpression)
		if string(jsonColumnReferenceExpression) == "{}" { // empty struct
			dst.ColumnReferenceExpression = nil
		} else {
			if err = validator.Validate(dst.ColumnReferenceExpression); err != nil {
				dst.ColumnReferenceExpression = nil
			} else {
				match++
			}
		}
	} else {
		dst.ColumnReferenceExpression = nil
	}

	// try to unmarshal data into ColumnarBinaryOperation
	err = newStrictDecoder(data).Decode(&dst.ColumnarBinaryOperation)
	if err == nil {
		jsonColumnarBinaryOperation, _ := json.Marshal(dst.ColumnarBinaryOperation)
		if string(jsonColumnarBinaryOperation) == "{}" { // empty struct
			dst.ColumnarBinaryOperation = nil
		} else {
			if err = validator.Validate(dst.ColumnarBinaryOperation); err != nil {
				dst.ColumnarBinaryOperation = nil
			} else {
				match++
			}
		}
	} else {
		dst.ColumnarBinaryOperation = nil
	}

	// try to unmarshal data into ColumnarUnaryOperation
	err = newStrictDecoder(data).Decode(&dst.ColumnarUnaryOperation)
	if err == nil {
		jsonColumnarUnaryOperation, _ := json.Marshal(dst.ColumnarUnaryOperation)
		if string(jsonColumnarUnaryOperation) == "{}" { // empty struct
			dst.ColumnarUnaryOperation = nil
		} else {
			if err = validator.Validate(dst.ColumnarUnaryOperation); err != nil {
				dst.ColumnarUnaryOperation = nil
			} else {
				match++
			}
		}
	} else {
		dst.ColumnarUnaryOperation = nil
	}

	// try to unmarshal data into Function
	err = newStrictDecoder(data).Decode(&dst.Function)
	if err == nil {
		jsonFunction, _ := json.Marshal(dst.Function)
		if string(jsonFunction) == "{}" { // empty struct
			dst.Function = nil
		} else {
			if err = validator.Validate(dst.Function); err != nil {
				dst.Function = nil
			} else {
				match++
			}
		}
	} else {
		dst.Function = nil
	}

	// try to unmarshal data into Literal
	err = newStrictDecoder(data).Decode(&dst.Literal)
	if err == nil {
		jsonLiteral, _ := json.Marshal(dst.Literal)
		if string(jsonLiteral) == "{}" { // empty struct
			dst.Literal = nil
		} else {
			if err = validator.Validate(dst.Literal); err != nil {
				dst.Literal = nil
			} else {
				match++
			}
		}
	} else {
		dst.Literal = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ColumnReferenceExpression = nil
		dst.ColumnarBinaryOperation = nil
		dst.ColumnarUnaryOperation = nil
		dst.Function = nil
		dst.Literal = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ColumnExpression)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ColumnExpression)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ColumnExpression) MarshalJSON() ([]byte, error) {
	if src.ColumnReferenceExpression != nil {
		return json.Marshal(&src.ColumnReferenceExpression)
	}

	if src.ColumnarBinaryOperation != nil {
		return json.Marshal(&src.ColumnarBinaryOperation)
	}

	if src.ColumnarUnaryOperation != nil {
		return json.Marshal(&src.ColumnarUnaryOperation)
	}

	if src.Function != nil {
		return json.Marshal(&src.Function)
	}

	if src.Literal != nil {
		return json.Marshal(&src.Literal)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ColumnExpression) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ColumnReferenceExpression != nil {
		return obj.ColumnReferenceExpression
	}

	if obj.ColumnarBinaryOperation != nil {
		return obj.ColumnarBinaryOperation
	}

	if obj.ColumnarUnaryOperation != nil {
		return obj.ColumnarUnaryOperation
	}

	if obj.Function != nil {
		return obj.Function
	}

	if obj.Literal != nil {
		return obj.Literal
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ColumnExpression) GetActualInstanceValue() (interface{}) {
	if obj.ColumnReferenceExpression != nil {
		return *obj.ColumnReferenceExpression
	}

	if obj.ColumnarBinaryOperation != nil {
		return *obj.ColumnarBinaryOperation
	}

	if obj.ColumnarUnaryOperation != nil {
		return *obj.ColumnarUnaryOperation
	}

	if obj.Function != nil {
		return *obj.Function
	}

	if obj.Literal != nil {
		return *obj.Literal
	}

	// all schemas are nil
	return nil
}

type NullableColumnExpression struct {
	value *ColumnExpression
	isSet bool
}

func (v NullableColumnExpression) Get() *ColumnExpression {
	return v.value
}

func (v *NullableColumnExpression) Set(val *ColumnExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableColumnExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableColumnExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableColumnExpression(val *ColumnExpression) *NullableColumnExpression {
	return &NullableColumnExpression{value: val, isSet: true}
}

func (v NullableColumnExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableColumnExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


