/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExecuteQueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecuteQueryRequest{}

// ExecuteQueryRequest Used to submit a new query for execution
type ExecuteQueryRequest struct {
	QueryDefinition QueryQueryDefinition `json:"queryDefinition"`
}

type _ExecuteQueryRequest ExecuteQueryRequest

// NewExecuteQueryRequest instantiates a new ExecuteQueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecuteQueryRequest(queryDefinition QueryQueryDefinition) *ExecuteQueryRequest {
	this := ExecuteQueryRequest{}
	this.QueryDefinition = queryDefinition
	return &this
}

// NewExecuteQueryRequestWithDefaults instantiates a new ExecuteQueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecuteQueryRequestWithDefaults() *ExecuteQueryRequest {
	this := ExecuteQueryRequest{}
	return &this
}

// GetQueryDefinition returns the QueryDefinition field value
func (o *ExecuteQueryRequest) GetQueryDefinition() QueryQueryDefinition {
	if o == nil {
		var ret QueryQueryDefinition
		return ret
	}

	return o.QueryDefinition
}

// GetQueryDefinitionOk returns a tuple with the QueryDefinition field value
// and a boolean to check if the value has been set.
func (o *ExecuteQueryRequest) GetQueryDefinitionOk() (*QueryQueryDefinition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QueryDefinition, true
}

// SetQueryDefinition sets field value
func (o *ExecuteQueryRequest) SetQueryDefinition(v QueryQueryDefinition) {
	o.QueryDefinition = v
}

func (o ExecuteQueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecuteQueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["queryDefinition"] = o.QueryDefinition
	return toSerialize, nil
}

func (o *ExecuteQueryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"queryDefinition",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExecuteQueryRequest := _ExecuteQueryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExecuteQueryRequest)

	if err != nil {
		return err
	}

	*o = ExecuteQueryRequest(varExecuteQueryRequest)

	return err
}

type NullableExecuteQueryRequest struct {
	value *ExecuteQueryRequest
	isSet bool
}

func (v NullableExecuteQueryRequest) Get() *ExecuteQueryRequest {
	return v.value
}

func (v *NullableExecuteQueryRequest) Set(val *ExecuteQueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExecuteQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExecuteQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecuteQueryRequest(val *ExecuteQueryRequest) *NullableExecuteQueryRequest {
	return &NullableExecuteQueryRequest{value: val, isSet: true}
}

func (v NullableExecuteQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecuteQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


