/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi2

import (
	"encoding/json"
)

// checks if the OrderByExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderByExpression{}

// OrderByExpression Description of ORDER BY clause in SELECT query
type OrderByExpression struct {
	// Index of the column from the columnClauses (0-based). We can Assume that ordering is done only on data that are results of the query.
	ColumnIndex *int32 `json:"columnIndex,omitempty"`
	Ascending *bool `json:"ascending,omitempty"`
}

// NewOrderByExpression instantiates a new OrderByExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderByExpression() *OrderByExpression {
	this := OrderByExpression{}
	return &this
}

// NewOrderByExpressionWithDefaults instantiates a new OrderByExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderByExpressionWithDefaults() *OrderByExpression {
	this := OrderByExpression{}
	return &this
}

// GetColumnIndex returns the ColumnIndex field value if set, zero value otherwise.
func (o *OrderByExpression) GetColumnIndex() int32 {
	if o == nil || IsNil(o.ColumnIndex) {
		var ret int32
		return ret
	}
	return *o.ColumnIndex
}

// GetColumnIndexOk returns a tuple with the ColumnIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderByExpression) GetColumnIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.ColumnIndex) {
		return nil, false
	}
	return o.ColumnIndex, true
}

// HasColumnIndex returns a boolean if a field has been set.
func (o *OrderByExpression) HasColumnIndex() bool {
	if o != nil && !IsNil(o.ColumnIndex) {
		return true
	}

	return false
}

// SetColumnIndex gets a reference to the given int32 and assigns it to the ColumnIndex field.
func (o *OrderByExpression) SetColumnIndex(v int32) {
	o.ColumnIndex = &v
}

// GetAscending returns the Ascending field value if set, zero value otherwise.
func (o *OrderByExpression) GetAscending() bool {
	if o == nil || IsNil(o.Ascending) {
		var ret bool
		return ret
	}
	return *o.Ascending
}

// GetAscendingOk returns a tuple with the Ascending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderByExpression) GetAscendingOk() (*bool, bool) {
	if o == nil || IsNil(o.Ascending) {
		return nil, false
	}
	return o.Ascending, true
}

// HasAscending returns a boolean if a field has been set.
func (o *OrderByExpression) HasAscending() bool {
	if o != nil && !IsNil(o.Ascending) {
		return true
	}

	return false
}

// SetAscending gets a reference to the given bool and assigns it to the Ascending field.
func (o *OrderByExpression) SetAscending(v bool) {
	o.Ascending = &v
}

func (o OrderByExpression) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderByExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ColumnIndex) {
		toSerialize["columnIndex"] = o.ColumnIndex
	}
	if !IsNil(o.Ascending) {
		toSerialize["ascending"] = o.Ascending
	}
	return toSerialize, nil
}

type NullableOrderByExpression struct {
	value *OrderByExpression
	isSet bool
}

func (v NullableOrderByExpression) Get() *OrderByExpression {
	return v.value
}

func (v *NullableOrderByExpression) Set(val *OrderByExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderByExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderByExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderByExpression(val *OrderByExpression) *NullableOrderByExpression {
	return &NullableOrderByExpression{value: val, isSet: true}
}

func (v NullableOrderByExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderByExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


