/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SelectQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SelectQuery{}

// SelectQuery Description of a select query
type SelectQuery struct {
	ColumnClauses []ColumnExpression `json:"columnClauses"`
	WhereClause *ColumnExpression `json:"whereClause,omitempty"`
	OrderByClause []OrderByExpression `json:"orderByClause,omitempty"`
	LimitClause *LimitExpression `json:"limitClause,omitempty"`
}

type _SelectQuery SelectQuery

// NewSelectQuery instantiates a new SelectQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSelectQuery(columnClauses []ColumnExpression) *SelectQuery {
	this := SelectQuery{}
	this.ColumnClauses = columnClauses
	return &this
}

// NewSelectQueryWithDefaults instantiates a new SelectQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSelectQueryWithDefaults() *SelectQuery {
	this := SelectQuery{}
	return &this
}

// GetColumnClauses returns the ColumnClauses field value
func (o *SelectQuery) GetColumnClauses() []ColumnExpression {
	if o == nil {
		var ret []ColumnExpression
		return ret
	}

	return o.ColumnClauses
}

// GetColumnClausesOk returns a tuple with the ColumnClauses field value
// and a boolean to check if the value has been set.
func (o *SelectQuery) GetColumnClausesOk() ([]ColumnExpression, bool) {
	if o == nil {
		return nil, false
	}
	return o.ColumnClauses, true
}

// SetColumnClauses sets field value
func (o *SelectQuery) SetColumnClauses(v []ColumnExpression) {
	o.ColumnClauses = v
}

// GetWhereClause returns the WhereClause field value if set, zero value otherwise.
func (o *SelectQuery) GetWhereClause() ColumnExpression {
	if o == nil || IsNil(o.WhereClause) {
		var ret ColumnExpression
		return ret
	}
	return *o.WhereClause
}

// GetWhereClauseOk returns a tuple with the WhereClause field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelectQuery) GetWhereClauseOk() (*ColumnExpression, bool) {
	if o == nil || IsNil(o.WhereClause) {
		return nil, false
	}
	return o.WhereClause, true
}

// HasWhereClause returns a boolean if a field has been set.
func (o *SelectQuery) HasWhereClause() bool {
	if o != nil && !IsNil(o.WhereClause) {
		return true
	}

	return false
}

// SetWhereClause gets a reference to the given ColumnExpression and assigns it to the WhereClause field.
func (o *SelectQuery) SetWhereClause(v ColumnExpression) {
	o.WhereClause = &v
}

// GetOrderByClause returns the OrderByClause field value if set, zero value otherwise.
func (o *SelectQuery) GetOrderByClause() []OrderByExpression {
	if o == nil || IsNil(o.OrderByClause) {
		var ret []OrderByExpression
		return ret
	}
	return o.OrderByClause
}

// GetOrderByClauseOk returns a tuple with the OrderByClause field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelectQuery) GetOrderByClauseOk() ([]OrderByExpression, bool) {
	if o == nil || IsNil(o.OrderByClause) {
		return nil, false
	}
	return o.OrderByClause, true
}

// HasOrderByClause returns a boolean if a field has been set.
func (o *SelectQuery) HasOrderByClause() bool {
	if o != nil && !IsNil(o.OrderByClause) {
		return true
	}

	return false
}

// SetOrderByClause gets a reference to the given []OrderByExpression and assigns it to the OrderByClause field.
func (o *SelectQuery) SetOrderByClause(v []OrderByExpression) {
	o.OrderByClause = v
}

// GetLimitClause returns the LimitClause field value if set, zero value otherwise.
func (o *SelectQuery) GetLimitClause() LimitExpression {
	if o == nil || IsNil(o.LimitClause) {
		var ret LimitExpression
		return ret
	}
	return *o.LimitClause
}

// GetLimitClauseOk returns a tuple with the LimitClause field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelectQuery) GetLimitClauseOk() (*LimitExpression, bool) {
	if o == nil || IsNil(o.LimitClause) {
		return nil, false
	}
	return o.LimitClause, true
}

// HasLimitClause returns a boolean if a field has been set.
func (o *SelectQuery) HasLimitClause() bool {
	if o != nil && !IsNil(o.LimitClause) {
		return true
	}

	return false
}

// SetLimitClause gets a reference to the given LimitExpression and assigns it to the LimitClause field.
func (o *SelectQuery) SetLimitClause(v LimitExpression) {
	o.LimitClause = &v
}

func (o SelectQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SelectQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["columnClauses"] = o.ColumnClauses
	if !IsNil(o.WhereClause) {
		toSerialize["whereClause"] = o.WhereClause
	}
	if !IsNil(o.OrderByClause) {
		toSerialize["orderByClause"] = o.OrderByClause
	}
	if !IsNil(o.LimitClause) {
		toSerialize["limitClause"] = o.LimitClause
	}
	return toSerialize, nil
}

func (o *SelectQuery) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"columnClauses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSelectQuery := _SelectQuery{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSelectQuery)

	if err != nil {
		return err
	}

	*o = SelectQuery(varSelectQuery)

	return err
}

type NullableSelectQuery struct {
	value *SelectQuery
	isSet bool
}

func (v NullableSelectQuery) Get() *SelectQuery {
	return v.value
}

func (v *NullableSelectQuery) Set(val *SelectQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableSelectQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableSelectQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSelectQuery(val *SelectQuery) *NullableSelectQuery {
	return &NullableSelectQuery{value: val, isSet: true}
}

func (v NullableSelectQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSelectQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


