/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MultipleProblemsErrorProblemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultipleProblemsErrorProblemsInner{}

// MultipleProblemsErrorProblemsInner struct for MultipleProblemsErrorProblemsInner
type MultipleProblemsErrorProblemsInner struct {
	// Description of particular problem
	Error string `json:"error"`
	// Optional context for user (for e.g. which column caused problem). It can be helpful for troubleshooting.
	Context *string `json:"context,omitempty"`
}

type _MultipleProblemsErrorProblemsInner MultipleProblemsErrorProblemsInner

// NewMultipleProblemsErrorProblemsInner instantiates a new MultipleProblemsErrorProblemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultipleProblemsErrorProblemsInner(error_ string) *MultipleProblemsErrorProblemsInner {
	this := MultipleProblemsErrorProblemsInner{}
	this.Error = error_
	return &this
}

// NewMultipleProblemsErrorProblemsInnerWithDefaults instantiates a new MultipleProblemsErrorProblemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultipleProblemsErrorProblemsInnerWithDefaults() *MultipleProblemsErrorProblemsInner {
	this := MultipleProblemsErrorProblemsInner{}
	return &this
}

// GetError returns the Error field value
func (o *MultipleProblemsErrorProblemsInner) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *MultipleProblemsErrorProblemsInner) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *MultipleProblemsErrorProblemsInner) SetError(v string) {
	o.Error = v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *MultipleProblemsErrorProblemsInner) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultipleProblemsErrorProblemsInner) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *MultipleProblemsErrorProblemsInner) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *MultipleProblemsErrorProblemsInner) SetContext(v string) {
	o.Context = &v
}

func (o MultipleProblemsErrorProblemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultipleProblemsErrorProblemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	return toSerialize, nil
}

func (o *MultipleProblemsErrorProblemsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMultipleProblemsErrorProblemsInner := _MultipleProblemsErrorProblemsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMultipleProblemsErrorProblemsInner)

	if err != nil {
		return err
	}

	*o = MultipleProblemsErrorProblemsInner(varMultipleProblemsErrorProblemsInner)

	return err
}

type NullableMultipleProblemsErrorProblemsInner struct {
	value *MultipleProblemsErrorProblemsInner
	isSet bool
}

func (v NullableMultipleProblemsErrorProblemsInner) Get() *MultipleProblemsErrorProblemsInner {
	return v.value
}

func (v *NullableMultipleProblemsErrorProblemsInner) Set(val *MultipleProblemsErrorProblemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMultipleProblemsErrorProblemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMultipleProblemsErrorProblemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultipleProblemsErrorProblemsInner(val *MultipleProblemsErrorProblemsInner) *NullableMultipleProblemsErrorProblemsInner {
	return &NullableMultipleProblemsErrorProblemsInner{value: val, isSet: true}
}

func (v NullableMultipleProblemsErrorProblemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultipleProblemsErrorProblemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


