/*
MIMUW ISBD database system

This file describes interface between DBMS system and user.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi2

import (
	"encoding/json"
)

// checks if the ColumnReferenceExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ColumnReferenceExpression{}

// ColumnReferenceExpression Description of a reference to a column used in column expression
type ColumnReferenceExpression struct {
	TableName *string `json:"tableName,omitempty"`
	ColumnName *string `json:"columnName,omitempty"`
}

// NewColumnReferenceExpression instantiates a new ColumnReferenceExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewColumnReferenceExpression() *ColumnReferenceExpression {
	this := ColumnReferenceExpression{}
	return &this
}

// NewColumnReferenceExpressionWithDefaults instantiates a new ColumnReferenceExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewColumnReferenceExpressionWithDefaults() *ColumnReferenceExpression {
	this := ColumnReferenceExpression{}
	return &this
}

// GetTableName returns the TableName field value if set, zero value otherwise.
func (o *ColumnReferenceExpression) GetTableName() string {
	if o == nil || IsNil(o.TableName) {
		var ret string
		return ret
	}
	return *o.TableName
}

// GetTableNameOk returns a tuple with the TableName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColumnReferenceExpression) GetTableNameOk() (*string, bool) {
	if o == nil || IsNil(o.TableName) {
		return nil, false
	}
	return o.TableName, true
}

// HasTableName returns a boolean if a field has been set.
func (o *ColumnReferenceExpression) HasTableName() bool {
	if o != nil && !IsNil(o.TableName) {
		return true
	}

	return false
}

// SetTableName gets a reference to the given string and assigns it to the TableName field.
func (o *ColumnReferenceExpression) SetTableName(v string) {
	o.TableName = &v
}

// GetColumnName returns the ColumnName field value if set, zero value otherwise.
func (o *ColumnReferenceExpression) GetColumnName() string {
	if o == nil || IsNil(o.ColumnName) {
		var ret string
		return ret
	}
	return *o.ColumnName
}

// GetColumnNameOk returns a tuple with the ColumnName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ColumnReferenceExpression) GetColumnNameOk() (*string, bool) {
	if o == nil || IsNil(o.ColumnName) {
		return nil, false
	}
	return o.ColumnName, true
}

// HasColumnName returns a boolean if a field has been set.
func (o *ColumnReferenceExpression) HasColumnName() bool {
	if o != nil && !IsNil(o.ColumnName) {
		return true
	}

	return false
}

// SetColumnName gets a reference to the given string and assigns it to the ColumnName field.
func (o *ColumnReferenceExpression) SetColumnName(v string) {
	o.ColumnName = &v
}

func (o ColumnReferenceExpression) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ColumnReferenceExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TableName) {
		toSerialize["tableName"] = o.TableName
	}
	if !IsNil(o.ColumnName) {
		toSerialize["columnName"] = o.ColumnName
	}
	return toSerialize, nil
}

type NullableColumnReferenceExpression struct {
	value *ColumnReferenceExpression
	isSet bool
}

func (v NullableColumnReferenceExpression) Get() *ColumnReferenceExpression {
	return v.value
}

func (v *NullableColumnReferenceExpression) Set(val *ColumnReferenceExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableColumnReferenceExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableColumnReferenceExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableColumnReferenceExpression(val *ColumnReferenceExpression) *NullableColumnReferenceExpression {
	return &NullableColumnReferenceExpression{value: val, isSet: true}
}

func (v NullableColumnReferenceExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableColumnReferenceExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


